spring:
  application:
    name: customer-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/customer_account
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
